drop table categoria;
create table categoria (
	id_categoria int generated by default as identity,
	tipo varchar(100) not null,
	primary key (id_categoria)
);
insert into categoria (tipo) values ('Impiegato'), ('Quadro'), ('Dirigente');
select * from categoria c 

create table ruole (
	id_ruole int generated by default as identity,
	stipendio_minimo numeric(10) not null,
	descrizione varchar(100) not null,
	primary key (id_ruole)

)
insert into ruole (stipendio_minimo, descrizione) values
	(1000, 'amministrazione'),
	(1200, 'tecnico'),
	(1300, 'svilupatore'),
	(1800, 'capo progetto'),
	(2000, 'commerciale')
select * from ruole;	

create table contratto(
	id_contratto int generated by default as identity,
	id_categoria int,
	id_ruole int,
	stipendio numeric(10) not null,
	data_assunzione date,
	data_dimisione date,
	primary key(id_contratto),
	foreign key (id_categoria) references categoria(id_categoria),
	foreign key (id_ruole) references ruole(id_ruole)
)

create table employee(
	id int generated by default as identity,
	id_contratto int,
	country varchar(50) not null,
	email varchar(50) not null,
	fullname varchar(50) not null,
	gender varchar(50) not null,
	address varchar(100),
	primary key (id),
	foreign key (id_contratto) references contratto(id_contratto)

)

/*
 * load contratti
 */
insert into contratto (stipendio, data_assunzione) values
	(1500, '2025-06-01'),
	(1600, '2025-07-01'),
	(1500, '2025-09-01'),
	(1200, '2026-01-10'),
	(2000, '2025-10-01'),
	(2100, '2027-02-01')
select * from contratto;
/*
 * load employee
 */
insert into employee (country, email, fullname, gender, address) values 
	('Italia', 'aa@tin.it', 'Marco Lettruca', 'maschio', 'via della Lune 10'),
	('Italia', 'bb@tin.it', 'Andrea Depardieu', 'maschio', 'Cosro corsic, 22'),
	('Italia', 'cc@tin.it', 'Paolo Rosso', 'maschio', 'Corso blue 10/4'),
	('Italia', 'dd@tin.it', 'Cinzia Verde', 'femmina', 'via Lagange 33'),
	('Italia', 'ee@tin.it', 'Alice Biance', 'femmina', 'Corso della Rosa 34'),
	('Italia', 'ff@tin.it', 'Giuseppe Lagrange', 'maschio', 'Corso Monte 33')
select * from employee;

/*
 * view step 1
 */
 create or replace view list_emplyee as  
	select e.id, e.fullname , e.gender, c.stipendio , c.data_assunzione,
		c2.tipo , r.descrizione  as ruolo, r.stipendio_minimo 
				from employee e
		left join contratto c on c.id_contratto  = e.id_contratto 
		left join categoria c2 on c2.id_categoria = c.id_categoria 
		left join ruolo r  on r.id_ruole = c.id_ruole
	
select * from list_emplyee;

/*
* creazione procedura step 2
*/
drop function find_employees_simple;
create or replace function find_employees_sample(stipendio_min numeric)
	returns table (
		id int,
		fullname varchar(50),
		data_assunzione Date,
		stipendio numeric,
		descrizione varchar(100),
		tipo varchar(100)
	) as $$
	begin
		return QUERY
		select e.id , e.fullname , c.data_assunzione , c.stipendio , r.descrizione ,
		c2.tipo    from employee e
		left join contratto c on c.id_contratto = e.id_contratto 
		left join categoria c2 on c2.id_categoria  = c.id_categoria 
		left join ruole r  on r.id_ruole = c.id_ruole	
		where c.stipendio > stipendio_min;
	end;
	$$ language plpgsql;
	
select * from find_employees_sample(1400);
/*
 *  creazioen dtored procedura step 3 
*/
create or replace procedure aumento_stipendi_per_ruolo(
	p_min_stipendio numeric,
	p_ruolo varchar(100)
	)
	language plpgsql
	as $$
	begin
		update contratto
			set stipendio = stipendio * 1.10
			where stipendio > p_min_stipendio
				and id_contratto in (
					select con.id_contratto from contratto con
						join ruole r on con.id_ruole = r.id_ruole
							where lower(r.descrizione) = lower(p_ruolo) 
				);	
	end;
	$$
	
call aumento_stipendi_per_ruolo(1300, 'svilupatore')

/*
 * parametri dentro un store procedure
 */
create or replace procedure insert_new_categoria()
language plpgsql
as $$
declare 
	v_new_cat varchar(100);
begin
	v_new_cat := 'store procedure';
	insert into categoria (tipo) values (v_new_cat);
end;
$$;

call insert_new_categoria();

/*
 *  definizione sp_employee 
*/	
create table sp_employee(
	id_emp int generated by default as identity,
	annual_salary numeric not null,
	hourly_rate numeric generated always as (annual_salary / 2080::numeric) stored null,
	primary key (id_emp)
)
insert into sp_employee (annual_salary) values (36000);
delete from sp_employee ;


/*
 * loop while
 *      exit  per uscire del while
 * 		continue rimane nel loop però salta il process
 * 		raise notice per avere un log
 */
create or replace procedure create_sp_employee(number_emp numeric)
language plpgsql
as $$
declare
	startPay numeric := 36000;
	emp_num numeric  := 0;
begin
	while (startPay < 200000) loop
		emp_num := emp_num + 1;
		if emp_num = number_emp then
			exit;
		end if;
		
		if emp_num % 2 = 0 then
			continue;
		end if;
		raise notice 'emp_id %', emp_num;

		insert into sp_employee (annual_salary) values (startPay);
		startPay := startPay + 5000;
	end loop;
end;
$$

call create_sp_employee(20);
delete from sp_employee;

/*
 * loop con for
 */
do
$$
	declare
		num int := 0;
	begin
		for num in 1..10 loop
			raise notice 'num %',num;
		end loop;
	end;
$$

-- esempio di conversione da farenhit in celsius

do
$$
	declare
		f int := 0.0;
		celsius float := 0.0;
		minimum int := 32;
		maximum int := 80;
		step    int := 2;
	begin
		for f in minimum..maximum by step loop
			celsius := (f-32.0) * (5.0 / 9.0);
			raise notice 'Ferenhit = % Celisius = % ', f,celsius::numeric(10,2);
		end loop;
	end;
$$;

/*
* commit /rollback
*/
create or replace procedure create_sp_employee(number_emp numeric)
language plpgsql
as $$
declare
	startPay numeric := 36000;
	emp_num numeric  := 0;
begin
	while (startPay < 200000) loop
		emp_num := emp_num + 1;
		if emp_num = number_emp then
			exit;
		end if;
		
		
		if (startPay < 0) then		
			raise exception 'stipendio non valido %', startpay;
		end if;

		raise notice 'emp_id %', emp_num;

		insert into sp_employee (annual_salary) values (startPay);
		startPay := startPay - 5000;
	end loop;
end;
$$

call create_sp_employee(10);

/*
 * trigger
*/
drop table employee_log;
create table employee_log(
	id_log int generated by default as identity,
	id int,
	id_contratto int,
	country varchar(50) not null,
	email varchar(50) not null,
	fullname varchar(50) not null,
	gender varchar(50) not null,
	address varchar(100),
	action varchar(10) not null,
	action_time timestamp default current_timestamp,
	primary key (id_log)
)
 /*
  * definizione della function utilizzata dal trigger
  */
create or replace function log_employee()
	returns trigger
	as $$
--	declare
--		azione varchar(10);
	begin
--		azione := TG_ARGV[0];     -- recupera il parametro passato dal trigger
		if TG_OP = 'DELETE' then
			insert into employee_log (id, id_contratto, country, email,fullname, gender, address, action)
				values
			(old.id, old.id_contratto, old.country, old.email,old.fullname, old.gender, old.address, TG_OP);
			 return old;
		else 
			insert into employee_log (id, id_contratto, country, email,fullname, gender, address, action)
			values
			(new.id, new.id_contratto, new.country, new.email,new.fullname, new.gender, new.address, TG_OP); 
			return new;
			end if;
	end;
	$$ language plpgsql;

/*
 * definizione del trigger
 * 
 * opzione disponibile
 * BEFORE INSERT
 * AFTER  INSERT
 * BEFORE UPDATE
 * AFTER  UPDATE
 * BEFORE DELETE
 * AFTER  DELETE
 */

create or replace trigger trigger_log_employee_insert
	after insert on employee
	for each row
		execute function log_employee();

insert into employee (country, email, fullname, gender, address) values 
	('Italia', 'tt@tin.it', 'Marco triggerato', 'maschio', 'via del Trigger 10');

insert into employee (country, email, fullname, gender, address, id_contratto) values 
	('Italia', 'tt1@tin.it', 'Giuglio triggerato', 'maschio', 'via del Contratto 10', 7);

insert into employee (country, email, fullname, gender, address, id_contratto) values 
	('Italia', 'tt2@tin.it', 'Cesare triggerato', 'maschio', 'via del Operazione 10', 7);

create or replace trigger trigger_log_employee_update
	after update on employee
	for each row
		execute function log_employee();

update employee set email='update@gmail,com' where id=9;

create or replace trigger trigger_log_employee_delete
	after delete on employee
	for each row
		execute function log_employee();

delete from employee where id=9;


/*
* log per contratto
*/

create table contratto_log (
	id int generated by default as IDENTITY,
	id_contratto int not null,
	id_categoria int,
	id_ruolo int,
	stipendio numeric(10) not null,
	data_assunzione date not null,
	data_dimisione date,
	azione varchar(10) not null,
	azione_time timestamp default  current_timestamp,

	primary key (id)
	);
	
-- funzione log per contratto
create or replace function log_contratto()
	returns trigger
	as $$
	begin
		if TG_OP = 'DELETE' then
			 INSERT INTO contratto_log(id_contratto,id_categoria,id_ruolo,stipendio,data_assunzione,data_dimisione,azione)
        	 VALUES (OLD.id_contratto,OLD.id_categoria,OLD.id_ruole,OLD.stipendio,OLD.data_assunzione,OLD.data_dimisione,TG_OP);
			 return old;
		else 
			INSERT INTO contratto_log(id_contratto,id_categoria,id_ruolo,stipendio,data_assunzione,data_dimisione,azione)
        	 VALUES (new.id_contratto,new.id_categoria,new.id_ruole,new.stipendio,new.data_assunzione,new.data_dimisione,TG_OP); 
			return new;
		end if;
	end;
	$$ language plpgsql;	

create or replace TRIGGER trigger_log_contratto
	after INSERT or UPDATE or delete on contratto
		for each row
		execute function log_contratto();

insert into contratto (stipendio, data_assunzione, id_ruole, id_categoria) values
	(1500, '2025-06-01', 3, 1)
	
update contratto set id_ruole=2 where id_contratto=10	
delete from contratto where id_contratto=10;	